#!/bin/bash

# QUICK SCRIPT TO RUN SQUEEZEDET
set -x

cd ~/lns/xiyan/squeezeDet/
source ~/lns/xiyan/venv/squeezeDet/bin/activate
nohup ./scripts/train.sh -net squeezeDet -train_dir ~/lns/xiyan/training-logs/ -gpu 1 &> nohup_train.out &
nohup ./scripts/eval.sh -net squeezeDet -eval_dir ~/lns/xiyan/training-logs/ -image_set val -gpu 2 &> nohup_eval.out &
